"""
Submit LLM batch imputation job to Claude Batch API.

This script submits the batch request file generated by impute_missing_metadata.py
to the Claude Batch API and returns a batch ID for tracking.

Usage:
  python scripts/app/submit_llm_batch.py --input data/llm_batch_requests.jsonl

Requires: anthropic>=0.34 and ANTHROPIC_API_KEY environment variable
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

try:
    from anthropic import Anthropic
except ImportError:
    print("Error: anthropic package not found. Install with:")
    print("  pip install -r requirements-llm.txt")
    sys.exit(1)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True,
                       help="Input JSONL file with batch requests")
    parser.add_argument("--api-key", type=str, default=None,
                       help="Anthropic API key (or set ANTHROPIC_API_KEY env var)")
    return parser.parse_args()


def get_api_key(args_api_key: str | None) -> str:
    """Get API key from args or environment, prompting if necessary."""
    api_key = args_api_key or os.environ.get("ANTHROPIC_API_KEY")

    if not api_key:
        print("\nNo API key found in environment variable ANTHROPIC_API_KEY")
        api_key = input("Enter your Anthropic API key: ").strip()

        if not api_key:
            print("Error: API key is required")
            sys.exit(1)

    return api_key


def main() -> None:
    args = parse_args()

    if not args.input.exists():
        print(f"Error: Input file not found: {args.input}")
        sys.exit(1)

    # Get API key
    api_key = get_api_key(args.api_key)

    # Initialize client
    client = Anthropic(api_key=api_key)

    print(f"Submitting batch request from {args.input}")
    print("This may take a few seconds...")

    try:
        # Read the batch file and parse JSONL into list
        import json
        requests_list = []
        with args.input.open("r") as f:
            for line in f:
                line = line.strip()
                if line:
                    requests_list.append(json.loads(line))

        if not requests_list:
            print(f"Error: No requests found in {args.input}")
            sys.exit(1)

        print(f"Parsed {len(requests_list)} requests from file")

        # Create the batch
        batch = client.messages.batches.create(
            requests=requests_list
        )

        print(f"\n✓ Batch submitted successfully!")
        print(f"  Batch ID: {batch.id}")
        print(f"  Status: {batch.processing_status}")
        print(f"  Created at: {batch.created_at}")
        print(f"  Request counts: {batch.request_counts}")

        print(f"\nTo check status:")
        print(f"  python scripts/app/check_llm_batch.py --batch-id {batch.id}")

        print(f"\nTo download results when complete:")
        print(f"  python scripts/app/download_llm_batch.py --batch-id {batch.id} --output data/llm_batch_results.jsonl")

        # Save batch ID for convenience
        batch_id_file = args.input.parent / f"{args.input.stem}_batch_id.txt"
        batch_id_file.write_text(batch.id)
        print(f"\nBatch ID saved to: {batch_id_file}")

    except Exception as e:
        print(f"\nError submitting batch: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
